/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Submission" CASCADE;

DROP TABLE IF EXISTS "StarterProgram" CASCADE;

DROP TABLE IF EXISTS "User" CASCADE;

DROP TABLE IF EXISTS "Problem" CASCADE;

DROP TABLE IF EXISTS "Language" CASCADE;

CREATE TABLE "Language" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "is_archived" BOOLEAN NOT NULL,
  "language_code" INTEGER NOT NULL);

CREATE TABLE "Problem" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "difficulty" INTEGER NOT NULL,
  "problem_statement" TEXT NOT NULL,
  "problem_statement_type" INTEGER NOT NULL,
  "tests_type" INTEGER NOT NULL,
  "tests_version" TEXT NOT NULL,
  "compact_tests" TEXT NOT NULL,
  "complete_tests" TEXT NOT NULL);

CREATE TABLE "User" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "username" TEXT NOT NULL,
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "grade" TEXT NOT NULL,
  "school" TEXT NOT NULL);

CREATE TABLE "StarterProgram" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "language_code" INTEGER NOT NULL,
  "program" TEXT NOT NULL,
  "problem" BIGINT NOT NULL,
  CONSTRAINT "problem_fk"
    FOREIGN KEY ("problem")
    REFERENCES "Problem" ("id")
    INITIALLY DEFERRED);

CREATE TABLE "Submission" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "source_code" TEXT NOT NULL,
  "language" BIGINT NOT NULL,
  "is_compact_run" BOOLEAN NOT NULL,
  "tests_type" INTEGER NOT NULL,
  "tests_version" TEXT NOT NULL,
  "user" BIGINT NOT NULL,
  "problem" BIGINT NOT NULL,
  CONSTRAINT "language_fk"
    FOREIGN KEY ("language")
    REFERENCES "Language" ("id")
    INITIALLY DEFERRED,
  CONSTRAINT "user_fk"
    FOREIGN KEY ("user")
    REFERENCES "User" ("id")
    INITIALLY DEFERRED,
  CONSTRAINT "problem_fk"
    FOREIGN KEY ("problem")
    REFERENCES "Problem" ("id")
    INITIALLY DEFERRED);

